In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/Diabetes Missing Data.csv")

In [ ]:
#Standardize Column Names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
#Handling Missing Values

#Detect Missing Values
df.isnull().sum()

pregnant             0
glucose              0
diastolic_bp         0
skin_fold            0
serum_insulin        0
bmi                  0
diabetes_pedigree    0
age                  0
class                0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#Drop Missing Values
df_drop = df.dropna()

In [ ]:
df_drop_col = df.dropna(axis=1)

In [ ]:
#Fill Missing Values (Imputation)
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].mean())

In [ ]:
#Fill with Median
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
#Fill with Mode (Categorical Columns)
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
#Fill with Constant Value
df.fillna(0, inplace=True)

In [ ]:
df.dtypes

Pregnant               int64
Glucose              float64
Diastolic_BP         float64
Skin_Fold            float64
Serum_Insulin        float64
BMI                  float64
Diabetes_Pedigree    float64
Age                    int64
Class                  int64
dtype: object

In [ ]:
#Fix Data Types
df[col] = pd.to_numeric(df[col], errors='coerce')

In [46]:
# Fix numeric columns
numeric_cols = [
    "Pregnant", "Glucose", "Diastolic_BP", "Skin_Fold",
    "Serum_Insulin", "BMI", "Diabetes_Pedigree", "Age", "Class"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Parse date columns automatically (if present)
for col in df.columns:
    if "date" in col.lower():
        df[col] = pd.to_datetime(df[col], errors="coerce")

# Verify datatypes
print(df.dtypes)

Pregnant               int64
Glucose              float64
Diastolic_BP         float64
Skin_Fold            float64
Serum_Insulin        float64
BMI                  float64
Diabetes_Pedigree    float64
Age                    int64
Class                  int64
dtype: object

In [47]:
#Remove duplicate rows
df = df.drop_duplicates()

#Standardize column names
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_", regex=False)
      .str.replace(r"[^a-z0-9_]", "", regex=True)
)

# Verify changes
print(df.shape)
print(df.columns)

(768, 9)
Index(['pregnant', 'glucose', 'diastolic_bp', 'skin_fold', 'serum_insulin',
       'bmi', 'diabetes_pedigree', 'age', 'class'],
      dtype='object')

In [49]:
# Save cleaned dataset
df.to_csv("diabetes_cleaned.csv", index=False)

# Cleaning log
cleaning_log = {
    "initial_rows": initial_shape[0],
    "final_rows": final_shape[0],
    "duplicates_removed": initial_shape[0] - final_shape[0],
    "column_standardization": "lowercase + snake_case",
    "datatype_fix": "numeric coercion, invalid → NaN"
}

print(cleaning_log)

{'initial_rows': 768, 'final_rows': 768, 'duplicates_removed': 0, 'column_standardization': 'lowercase + snake_case', 'datatype_fix': 'numeric coercion, invalid → NaN'}